### PR TITLE
Paper Review #1: "Align With Purpose" ICLR 2024

### PR DESCRIPTION
**Pull request by y-zyy**
[Align With Purpose ICLR 2024.pdf](https://github.com/HIL-ASR/Paper_log/files/14718351/Align.With.Purpose.ICLR.2024.pdf)

Align With Purpose pic 1

### CODE REVIEW

**Comment by gipder** [comment]
@y-zyy 
What is the main idea of the paper?

**Comment by y-zyy** [comment]
@gipder 
I will upload the summary of this paper soon!

**Review by gipder — APPROVED** [review]
LGTM

**Comment by gipder** [comment]
@jykang0332 Could you please review this PR?

**Pull request merged**
